sudo: required
services:
  - docker

before_install:
  - docker build -t dbaker7532/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dbaker7532/react-test npm test

after_success:
  - docker build -t dbaker7532/multi-client ./client
  - docker build -t dbaker7532/multi-nginx ./nginx
  - docker build -t dbaker7532/multi-server ./server
  - docker build -t dbaker7532/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push dbaker7532/multi-client
  - docker push dbaker7532/multi-nginx
  - docker push dbaker7532/multi-server
  - docker push dbaker7532/multi-worker
  